describe('Send money with sufficient balance', () => {
  it('Should send money successfully', () => {
    cy.visit('http://localhost:3000')
    cy.get('[data-test="signin-username"]').type('Heath93')
    cy.get('[data-test="signin-password"]').type('s3cret')
    cy.get('[data-test="signin-submit"]').click()
    cy.url().should('not.include', '/signin')
    cy.get('[data-test="nav-top-new-transaction"]').click()
    cy.get('[data-test="user-list-search-input"]').type('Dina20')
    cy.wait(1000)
    cy.get('[data-test*="user-list-item-"]').first().click()
    cy.wait(2000)
    cy.get('input[placeholder="Amount"]').type('10')
    cy.get('input[placeholder="Add a note"]').type('Test payment')
    cy.get('[data-test="transaction-create-submit-payment"]').click()
    cy.get('[data-test="alert-bar-success"]').should('be.visible')
  })
})

describe('Send money with insufficient balance', () => {
  it('Should not allow payment with invalid amount', () => {
    cy.visit('http://localhost:3000')
    cy.get('[data-test="signin-username"]').type('Heath93')
    cy.get('[data-test="signin-password"]').type('s3cret')
    cy.get('[data-test="signin-submit"]').click()
    cy.url().should('not.include', '/signin')
    cy.get('[data-test="nav-top-new-transaction"]').click()
    cy.get('[data-test="user-list-search-input"]').type('Dina20')
    cy.wait(1000)
    cy.get('[data-test*="user-list-item-"]').first().click()
    cy.wait(2000)
    cy.get('input[placeholder="Add a note"]').type('Test payment')
    cy.wait(500)
    cy.get('[data-test="transaction-create-submit-payment"]').should('be.disabled')
  })
})
